#!/usr/bin/env bash
# create_migration.sh
# Creates an eleventy/migration branch with Eleventy + Tailwind scaffold,
# commits files, and pushes to origin. If the remote branch exists you'll be asked
# whether to overwrite it.
#
# Run this from the root of your local repository:
#   chmod +x create_migration.sh
#   ./create_migration.sh
set -euo pipefail

BRANCH="eleventy/migration"
REMOTE="origin"

echo "== Eleventy + Tailwind scaffold creator =="
echo

# Basic environment checks
if ! command -v git >/dev/null 2>&1; then
  echo "Error: git is required but not found in PATH." >&2
  exit 1
fi

# Check we are in a git repo
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Error: this script must be run from inside a git repository." >&2
  exit 1
fi

# Ensure remote exists
if ! git remote get-url "$REMOTE" >/dev/null 2>&1; then
  echo "Error: git remote '$REMOTE' not found. Set up the remote (e.g., git remote add origin <url>) and try again." >&2
  exit 1
fi

# Fetch latest
echo "Fetching from remote..."
git fetch "$REMOTE" --prune

# Determine base branch to create from (try main, fallback to master, else current)
BASE="main"
if git show-ref --verify --quiet "refs/remotes/${REMOTE}/${BASE}"; then
  echo "Using ${BASE} as base for new branch."
elif git show-ref --verify --quiet "refs/remotes/${REMOTE}/master"; then
  BASE="master"
  echo "Using ${BASE} as base for new branch."
else
  echo "Warning: could not find 'main' or 'master' on remote. Using current branch as base."
  BASE="$(git rev-parse --abbrev-ref HEAD)"
  echo "Base branch: ${BASE}"
fi

# Check whether remote branch exists
REMOTE_HAS_BRANCH=false
if git ls-remote --heads "$REMOTE" "$BRANCH" | grep -q "$BRANCH"; then
  REMOTE_HAS_BRANCH=true
fi

if $REMOTE_HAS_BRANCH; then
  echo
  read -r -p "Remote branch '$BRANCH' already exists. Overwrite it with this scaffold? (y/N): " yn
  case "$yn" in
    [Yy]* ) echo "Will overwrite remote branch $BRANCH.";;
    * ) echo "Aborting. No changes were made."; exit 0;;
  esac
fi

# Create and switch to branch (based on base)
git checkout -B "$BRANCH" "remotes/${REMOTE}/${BASE}" 2>/dev/null || git checkout -B "$BRANCH" "$BASE"

echo "Switched to branch: $(git rev-parse --abbrev-ref HEAD)"
echo

# Create directories
mkdir -p _includes/partials _includes/layouts _data src assets/css .github/workflows images

# Write files
cat > .eleventy.js <<'EOF'
module.exports = function(eleventyConfig) {
  // Passthrough for static assets (images, fonts, etc.)
  eleventyConfig.addPassthroughCopy("assets");
  eleventyConfig.addPassthroughCopy("images");

  // Filter for current year
  eleventyConfig.addFilter("year", () => new Date().getFullYear());

  return {
    dir: {
      input: "src",
      includes: "_includes",
      data: "_data",
      output: "dist"
    },
    passthroughFileCopy: true
  };
};
EOF

cat > package.json <<'EOF'
{
  "name": "portfolio-eleventy",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "eleventy --serve",
    "build:css": "tailwindcss -i ./assets/css/tailwind.css -o ./assets/css/style.css --minify",
    "build": "npm run build:css && eleventy",
    "start": "npm run dev"
  },
  "devDependencies": {
    "@11ty/eleventy": "^1.0.0",
    "autoprefixer": "^10.4.0",
    "postcss": "^8.4.0",
    "tailwindcss": "^3.0.0"
  }
}
EOF

cat > tailwind.config.js <<'EOF'
module.exports = {
  content: ["./src/**/*.{html,md,njk}", "./_includes/**/*.{njk,html}"],
  theme: {
    extend: {
      colors: {
        accent: '#0ea5a4'
      }
    }
  },
  plugins: []
};
EOF

cat > assets/css/tailwind.css <<'EOF'
@tailwind base;
@tailwind components;
@tailwind utilities;

/* Minimal design tokens / container width */
:root {
  --container-width: 1100px;
}
EOF

cat > assets/css/style.css <<'EOF'
/* This file is generated by the Tailwind CLI from assets/css/tailwind.css.
   It is safe to include as a placeholder; the CI build will overwrite it.
*/
@tailwind base;
@tailwind components;
@tailwind utilities;
EOF

cat > _includes/layouts/base.njk <<'EOF'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>{{ title | default("Andrew Orsak | Multimedia Specialist | Video Producer | Digital Creator") }}</title>
  <link rel="stylesheet" href="/assets/css/style.css">
</head>
<body class="bg-white text-slate-900 antialiased">
  {% include "partials/header.njk" %}
  <main id="content" class="max-w-[var(--container-width)] mx-auto px-4 py-8">
    {{ content | safe }}
  </main>
  {% include "partials/footer.njk" %}
</body>
</html>
EOF

cat > _includes/partials/header.njk <<'EOF'
<header class="border-b bg-slate-50">
  <div class="max-w-[var(--container-width)] mx-auto px-4 py-4 flex items-center justify-between">
    <a href="/" class="font-semibold text-lg">Andrew Orsak</a>
    <nav aria-label="Main navigation">
      <ul class="flex gap-4 text-sm text-slate-600">
        {% for item in navigation %}
          <li><a href="{{ item.url }}" class="hover:text-slate-900 {% if page.url == item.url %}font-medium{% endif %}">{{ item.label }}</a></li>
        {% endfor %}
      </ul>
    </nav>
  </div>
</header>
EOF

cat > _includes/partials/footer.njk <<'EOF'
<footer class="border-t bg-white">
  <div class="max-w-[var(--container-width)] mx-auto px-4 py-6 text-sm text-slate-600 text-center">
    <p>&copy; {{ "" | year }} Andrew Orsak. All rights reserved. — <a href="mailto:andreworsak@gmail.com" class="text-accent hover:underline">andreworsak@gmail.com</a></p>
  </div>
</footer>
EOF

cat > _data/navigation.json <<'EOF'
[
  { "label": "Home", "url": "/" },
  { "label": "Reel", "url": "/reel/" },
  { "label": "KindHealth", "url": "/kindhealth/" },
  { "label": "About", "url": "/about/" },
  { "label": "Contact", "url": "/contact/" }
]
EOF

cat > src/index.md <<'EOF'
---
title: Home
layout: layouts/base.njk
permalink: /
---
# Hi — I'm Andrew

Welcome to my portfolio. Replace this content with your homepage hero and highlights.  
You can list featured projects or a short bio here.
EOF

cat > src/reel.md <<'EOF'
---
title: Reel
layout: layouts/base.njk
permalink: /reel/
---
# Reel

Embed your showreel here — video embed, a thumbnail link, or a hosted player.  
Replace this with the content from your current reel page.
EOF

cat > src/kindhealth.md <<'EOF'
---
title: KindHealth
layout: layouts/base.njk
permalink: /kindhealth/
---
# KindHealth

Project page for KindHealth. Add screenshots, descriptions, your role, and links.
EOF

cat > src/about.md <<'EOF'
---
title: About
layout: layouts/base.njk
permalink: /about/
---
# About

Short bio, experience, skills, and links to social profiles.
EOF

cat > src/contact.md <<'EOF'
---
title: Contact
layout: layouts/base.njk
permalink: /contact/
---
# Contact

Email: [andreworsak@gmail.com](mailto:andreworsak@gmail.com)

(If you want a contact form later, we can add Netlify Forms or Formspree.)
EOF

cat > .github/workflows/preview-deploy.yml <<'EOF'
name: Preview deploy (eleventy migration)

on:
  push:
    branches:
      - eleventy/migration
  workflow_dispatch: {}

jobs:
  build-and-deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build CSS + Eleventy
        run: npm run build

      - name: Deploy to eleventy-preview branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: eleventy-preview
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
EOF

cat > .github/workflows/production-deploy.yml <<'EOF'
name: Production deploy (on main -> gh-pages)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build CSS + Eleventy
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
EOF

cat > .gitignore <<'EOF'
node_modules/
dist/
.env
.DS_Store
EOF

cat > README.md <<'EOF'
# Eleventy + Tailwind migration (migration branch)

Local dev:
1. npm ci
2. npm run dev

Build (production):
1. npm ci
2. npm run build
3. dist/ contains the generated site.

Workflows:
- preview-deploy.yml: builds on pushes to eleventy/migration and publishes dist to eleventy-preview.
- production-deploy.yml: builds on pushes to main and publishes dist to gh-pages.
EOF

echo "Files created. Preparing commit..."

git add .
git commit -m "chore(scaffold): Eleventy + Tailwind migration scaffold (preview + production workflows)" || {
  echo "No changes to commit (maybe the files already existed)."
}

# Push (confirm if remote branch exists)
if $REMOTE_HAS_BRANCH; then
  echo "Pushing and overwriting remote branch ${REMOTE}/${BRANCH}..."
  git push "$REMOTE" "$BRANCH" --force
else
  echo "Pushing new branch ${REMOTE}/${BRANCH}..."
  git push -u "$REMOTE" "$BRANCH"
fi

echo
echo "Done."
echo "The branch '$BRANCH' was pushed to '$REMOTE'."
echo
echo "What happens next:"
echo "- GitHub Actions (preview-deploy.yml) will run on pushes to $BRANCH and publish the generated site to branch 'eleventy-preview'."
echo "- The production workflow only runs on pushes to main and will publish to 'gh-pages' (safe; won't run from PR pushes)."
echo
echo "Local testing tips:"
echo "1) Install dependencies: npm ci"
echo "2) Start dev server: npm run dev (eleventy --serve)"
echo "3) Build locally: npm run build (generates ./dist)"
echo
echo "If you want me to generate a patch file instead of using this script, tell me and I will provide it."
